package Utilisateurs;

import Capitainerie.Capitainerie;
import Classes.Fonctions;
import Exceptions.LoginException;
import java.util.Hashtable;

/**
 *
 * @author Florent & Wadi
 */
public class Connexion extends javax.swing.JFrame {

    private static Hashtable<String, String> utilisateurs = new Hashtable<String, String>();

    /**
     * Creates new form Connexion
     */
    public Connexion() {
        initComponents();
        utilisateurs = Fonctions.getUtilisateurs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitreBienvenue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFNomUtilisateur = new javax.swing.JTextField();
        TFMdp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnValider = new javax.swing.JButton();
        BtnAnnuler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setAlwaysOnTop(true);
        setResizable(false);

        TitreBienvenue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TitreBienvenue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TitreBienvenue.setText("Bienvenue");
        TitreBienvenue.setToolTipText("");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nom d'utilisateur :");

        TFNomUtilisateur.setText("Admin");
        TFNomUtilisateur.setToolTipText("");

        TFMdp.setText("admin");

        jLabel3.setText("Mot de passe :");

        BtnValider.setText("Se connecter");
        BtnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValiderActionPerformed(evt);
            }
        });

        BtnAnnuler.setText("Annuler");
        BtnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnnulerActionPerformed(evt);
            }
        });

        jLabel1.setText("La capitainerie vous attend !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitreBienvenue)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnAnnuler, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFNomUtilisateur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFMdp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnValider, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TitreBienvenue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnValider)
                    .addComponent(BtnAnnuler))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValiderActionPerformed
        String nomUtilisateur = this.TFNomUtilisateur.getText();
        String motDePasse = this.TFMdp.getText();

        if (nomUtilisateur.isEmpty() || motDePasse.isEmpty()) {
            new LoginException("Erreur.", "Veuillez rentrer tous les champs.");
        } else if (utilisateurs.containsKey(nomUtilisateur) == false) {
            new LoginException("Erreur.", "Cet utilisateur n'existe pas.");
        } else if (!utilisateurs.get(nomUtilisateur).equals(motDePasse)) {
            new LoginException("Erreur.", "Le mot de passe est incorrect.");
        } else {
            Capitainerie capitainerie = new Capitainerie();
            capitainerie.setTitle("La Capitainerie - " + nomUtilisateur);
            capitainerie.setIsLoggedIn(true);
            capitainerie.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnValiderActionPerformed

    private void BtnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnnulerActionPerformed
        dispose();
    }//GEN-LAST:event_BtnAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnnuler;
    private javax.swing.JButton BtnValider;
    private javax.swing.JTextField TFMdp;
    private javax.swing.JTextField TFNomUtilisateur;
    private javax.swing.JLabel TitreBienvenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
