package Capitainerie;

import Classes.Bateau;
import Classes.Marin;
import Exceptions.CapitainerieException;
import Exceptions.SailorWithoutIdentificationException;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Month;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Florent & Wadi
 */
public class RemplirInfoBateau extends javax.swing.JDialog {

    private Bateau bateauARemplir;
    private Capitainerie capitainerie;

    /**
     * Creates new form BateauEntrant
     */
    public RemplirInfoBateau(Capitainerie parent, boolean modal, Bateau bateau, String emplacement) {
        super(parent, modal);
        initComponents();
        this.capitainerie = parent;
        this.bateauARemplir = bateau;
        this.LNomDuBateau.setText(bateau.getNom());
        this.LEmplacement.setText(emplacement);
        this.LPavillon.setText(bateau.getPavillon());
        this.TFPortDAttache.setText(bateau.getPortAttache());
        this.STonnage.setValue((Integer) bateau.getTonnage());

        DefaultListModel listModelEquipage = new DefaultListModel();
        listModelEquipage.addElement(bateau.getEquipage().getCapitaine());
        listModelEquipage.addElement(bateau.getEquipage().getSecond());
        for (int i = 0; i < bateau.getEquipage().getMarins().size(); i++) {
            listModelEquipage.addElement(bateau.getEquipage().getMarins().get(i));
        }
        this.LBEquipage.setModel(listModelEquipage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LEmplacement = new javax.swing.JLabel();
        LNomDuBateau = new javax.swing.JLabel();
        LPavillon = new javax.swing.JLabel();
        TFPortDAttache = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        STonnage = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LBEquipage = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CBFonction = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        TFNom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TFPrenom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        BtnSupprimerLeMarin = new javax.swing.JButton();
        BtnAjouterLeMarin = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        BtnValiderInformations = new javax.swing.JButton();
        CBJour = new javax.swing.JComboBox<>();
        CBMois = new javax.swing.JComboBox<>();
        CBAnnee = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Emplacement :");

        jLabel2.setText("Nom du bateau :");

        jLabel3.setText("Pavillon :");

        LEmplacement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LEmplacement.setText("P12*1");

        LNomDuBateau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LNomDuBateau.setText("Black Berry");

        LPavillon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LPavillon.setText("UK");

        jLabel7.setText("Port d'attache :");

        jLabel8.setText("Tonnage :");

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        jLabel9.setBackground(new java.awt.Color(220, 220, 220));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Informations sur le bateau");
        jLabel9.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(LBEquipage);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Équipage :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Bateau :");

        jLabel12.setText("Grade :");

        CBFonction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bosco", "Matelot", "Passager" }));

        jLabel13.setText("Nom :");

        jLabel14.setText("Prénom :");

        jLabel15.setText("Date de naissance :");

        BtnSupprimerLeMarin.setText("Supprimer le marin");
        BtnSupprimerLeMarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSupprimerLeMarinActionPerformed(evt);
            }
        });

        BtnAjouterLeMarin.setText("Ajouter le marin");
        BtnAjouterLeMarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjouterLeMarinActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Information marin:");

        BtnValiderInformations.setText("Valider les informations");
        BtnValiderInformations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValiderInformationsActionPerformed(evt);
            }
        });

        CBJour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        CBMois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        CBAnnee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFPortDAttache)
                            .addComponent(STonnage)
                            .addComponent(LEmplacement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LPavillon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LNomDuBateau, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(BtnValiderInformations, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(BtnSupprimerLeMarin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnAjouterLeMarin)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CBFonction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFNom, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TFPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(CBJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CBMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CBAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LNomDuBateau)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LEmplacement)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LPavillon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFPortDAttache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(STonnage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSupprimerLeMarin)
                            .addComponent(BtnValiderInformations)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnAjouterLeMarin)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnValiderInformationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValiderInformationsActionPerformed
        String portAttache = this.TFPortDAttache.getText();
        boolean valide = true;
        int tonnage = (Integer) this.STonnage.getValue();

        if (portAttache.length() > 0) {
            if (portAttache.length() <= 255) {
                this.bateauARemplir.setPortAttache(portAttache);
            } else {
                valide = false;
                new CapitainerieException("Erreur", "Le nom du port d'attache doit être inférieur à 255 caractères.");
            }
        } else {
            valide = false;
            new CapitainerieException("Erreur", "Le nom du port d'attache est requis.");
        }
        if (tonnage > 0) {
            this.bateauARemplir.setTonnage(tonnage);
        } else {
            valide = false;
            new CapitainerieException("Erreur", "Le tonnage du bateau doit être strictement positif.");
        }
        if (valide) {
            this.capitainerie.ajouterBateauListeBateauAmmare(bateauARemplir);
            this.dispose();
        }

    }//GEN-LAST:event_BtnValiderInformationsActionPerformed

    private void BtnSupprimerLeMarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSupprimerLeMarinActionPerformed
        int selectedIndex = this.LBEquipage.getSelectedIndex();
        if (selectedIndex >= 0) {
            if (selectedIndex <= 1) {
                new CapitainerieException("Erreur", "Vous ne pouvez pas supprimer le capitaine ou le second.");
            } else {
                ((DefaultListModel) this.LBEquipage.getModel()).remove(selectedIndex);
                this.bateauARemplir.getEquipage().getMarins().remove(selectedIndex - 2);
            }
        }
    }//GEN-LAST:event_BtnSupprimerLeMarinActionPerformed

    private void BtnAjouterLeMarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjouterLeMarinActionPerformed
        String nom = this.TFNom.getText();
        String prenom = this.TFPrenom.getText();

        if (nom.isEmpty() || prenom.isEmpty()) {
            new CapitainerieException("Erreur", "Veillez compléter le nom et le prénom.");
        } else {
            int ddn_jour = this.CBJour.getSelectedIndex() + 1;
            int ddn_mois = this.CBMois.getSelectedIndex() + 1;
            int ddn_annee = this.CBAnnee.getSelectedIndex() + 1900;
            System.out.println(this.CBFonction.getItemAt(this.CBFonction.getSelectedIndex()));
            try {
                LocalDate dateDeNaissance = LocalDate.of(ddn_annee, ddn_mois, ddn_jour);
                Marin marin = new Marin(nom, prenom, dateDeNaissance, Marin.Fonction.valueOf(this.CBFonction.getItemAt(this.CBFonction.getSelectedIndex())));
                this.bateauARemplir.getEquipage().getMarins().add(marin);
                ((DefaultListModel) this.LBEquipage.getModel()).addElement(marin);
            } catch (DateTimeException e) {
                new CapitainerieException("Erreur", "La date est invalide.");
            } catch (SailorWithoutIdentificationException e) {
                new CapitainerieException("Erreur", e.getMessage());
            } catch (Exception e) {
                new CapitainerieException("Erreur", e.getMessage());
            }
        }
    }//GEN-LAST:event_BtnAjouterLeMarinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAjouterLeMarin;
    private javax.swing.JButton BtnSupprimerLeMarin;
    private javax.swing.JButton BtnValiderInformations;
    private javax.swing.JComboBox<String> CBAnnee;
    private javax.swing.JComboBox<String> CBFonction;
    private javax.swing.JComboBox<String> CBJour;
    private javax.swing.JComboBox<String> CBMois;
    private javax.swing.JList<String> LBEquipage;
    private javax.swing.JLabel LEmplacement;
    private javax.swing.JLabel LNomDuBateau;
    private javax.swing.JLabel LPavillon;
    private javax.swing.JSpinner STonnage;
    private javax.swing.JTextField TFNom;
    private javax.swing.JTextField TFPortDAttache;
    private javax.swing.JTextField TFPrenom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
